import { chromium } from 'playwright'
const b = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required'] })
const ctx = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:2 })
const p = await ctx.newPage()
await p.goto('http://localhost:5199',{waitUntil:'load', timeout:60000})
await p.waitForFunction(() => !document.querySelector('[data-testid=gate] button[disabled]'), null, {timeout: 60000})
await p.click('text=Mit Ton betreten')
await p.waitForTimeout(2500)
const g1 = await p.evaluate(() => window.AudioManager.debugGains())
console.log('gains playing (Ducking aktiv):', JSON.stringify(g1))
const playing = await p.evaluate(() => window.AudioManager.playing && window.AudioManager.current.title)
console.log('track:', playing)
await p.screenshot({ path:'SVA_SCREENSHOTS/v3-musik-dock.png' })
// Pause -> Atmo wieder hoch (Ducking-Gegenprobe)
await p.evaluate(() => window.AudioManager.pause())
await p.waitForTimeout(1200)
console.log('gains paused (Atmo hoch):', JSON.stringify(await p.evaluate(() => window.AudioManager.debugGains())))
// Menü öffnen + Track wechseln
await p.click('img[alt*="Heimspiel"]')
await p.waitForTimeout(400)
await p.click('text=Dritte Halbzeit')
await p.waitForTimeout(800)
console.log('after select:', await p.evaluate(() => window.AudioManager.current.title), 'playing:', await p.evaluate(() => window.AudioManager.playing))
await p.screenshot({ path:'SVA_SCREENSHOTS/v3-musik-menu.png' })
await b.close()
