import { chromium } from 'playwright'
const b = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] })
const ctx = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:2 })
const p = await ctx.newPage()
await p.goto('http://localhost:5199',{waitUntil:'load', timeout:60000})
await p.waitForTimeout(2500)
await p.screenshot({ path:'SVA_SCREENSHOTS/v3-gate-choice.png' })
// „Mit Ton betreten"
await p.waitForFunction(() => !document.querySelector('[data-testid=gate] button[disabled]'), null, {timeout: 60000})
await p.click('text=Mit Ton betreten')
await p.waitForTimeout(500)
await p.screenshot({ path:'SVA_SCREENSHOTS/v3-gate-reveal.png' })
await p.waitForTimeout(900)
const state1 = await p.evaluate(() => ({ sound: localStorage.getItem('sva-sound'), gateOpen: window.useStore.getState().gateOpen, gateGone: !document.querySelector('[data-testid=gate]') }))
console.log('after WITH sound:', JSON.stringify(state1))
// Reload → Kurz-Tor (flash) und Auto-Open mit gemerkter Wahl
await p.reload({waitUntil:'load'})
await p.waitForTimeout(1200)
await p.screenshot({ path:'SVA_SCREENSHOTS/v3-gate-flash.png' })
await p.waitForFunction(() => !document.querySelector('[data-testid=gate]'), null, {timeout: 40000})
const state2 = await p.evaluate(() => ({ sound: window.useStore.getState().soundOn, gone: true }))
console.log('returning visitor:', JSON.stringify(state2))
await ctx.close() // CPU freigeben (SwiftShader)
const ctx2 = await b.newContext({ viewport:{width:1440,height:900} })
const p2 = await ctx2.newPage()
await p2.goto('http://localhost:5199',{waitUntil:'load', timeout:60000})
await p2.waitForFunction(() => !document.querySelector('[data-testid=gate] button[disabled]'), null, {timeout: 60000})
await p2.click('text=Ohne Ton')
await p2.waitForTimeout(1300)
console.log('after WITHOUT sound:', await p2.evaluate(() => localStorage.getItem('sva-sound')), 'soundOn:', await p2.evaluate(() => window.useStore.getState().soundOn))
await ctx2.close()
const ctx3 = await b.newContext({ viewport:{width:1440,height:900}, reducedMotion:'reduce' })
const p3 = await ctx3.newPage()
await p3.goto('http://localhost:5199',{waitUntil:'load', timeout:60000})
await p3.waitForTimeout(1500)
const rmGate = await p3.evaluate(() => !!document.querySelector('[data-testid=gate]'))
await p3.screenshot({ path:'SVA_SCREENSHOTS/v3-gate-fallback.png' })
console.log('reduced-motion gate visible:', rmGate)
await b.close()
